version: '3.1'


services:

  app:
    container_name: findtrip
    image: findtrip
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql

  dbpostgresql:
    container_name: postgres_db
    image: postgres
    volumes:
#        - ./postgres-data:/var/lib/postgresql/data
       - /var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=findtrip_db
    restart: always

volumes:
  postgres_data:
