version: '3.1'
services:

  app:
    container_name: findtrip
    image: findtrip
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql

  dbpostgresql:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=findtrip_db
#    restart: on-failure